codecov:
  notify:
    require_ci_to_pass: yes
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: "master, feature/codecov"
        flags: null
        paths: null
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

  coverage:
  notify:
