codecov:
  branch: feature/codecov
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2 # digits after decimal point to show % code coverage
  round: down
  range: "40...80" # scale the color plot range, red to green

  status:
    project: yes
    patch: yes
    changes: yes

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: null  # 1% # send message if coverage changes by more than this %
        only_pulls: false
        attachments: "sunburst, diff"
        branches: null  # "master, feature/codecov" # all branches by default
        flags: null
        paths: null

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
